### ISSUE TITLE
更新されていない旧site( https://covid19.codeforkagoshima.dev/ )?からの転送

### ISSUE THREAD

**Issue by matoken** [codeforkagoshima/covid19#103]
## 改善詳細 / Details of Improvement
- 更新されていない旧site( https://covid19.codeforkagoshima.dev/ )?からの転送．
東京都 新型コロナウイルス感染症対策サイトのページのフォークが鹿児島にあるかな?と　[FORKED_SITES.md](https://github.com/tokyo-metropolitan-gov/covid19/blob/master/FORKED_SITES.md) を参照したところ https://covid19.codeforkagoshima.dev/ が見つかりましたがこのページは更新されていないようです．(最終更新 2020/03/14 8:00)
GitHubへのリンクでこのリポジトリと https://covid19.code4kagoshima.org/ を見つけました．
旧siteから新siteへの転送を行ったほうが良さそうに思います．

(https://covid19.codeforkagoshima.dev/ がこのリポジトリと関係がなかったらすみません．)

**Comment by kurehajime** [comment]
途中で〜.devから〜.orgにサイトのURLを変更した…という経緯でした。
ご報告ありがとうございます。

@kentaro 
すみません、この件どうしましょうか？
301リダイレクトするか、でも両ドメインとも同じサーバーを見ていると思うので、DNSの設定で何とかするか…。

**Comment by kentaro** [comment]
元のサイトをクローズするようにしますー。

**Comment by kentaro** [comment]
もろもろ削除処理しました。ブラウザのキャッシュが残ってるとサイトが表示されているように見えるので、キャッシュを消す必要があるようです。

東京都のまとめにある鹿児島県版のドメインも新しい方に修正されてますね。
https://github.com/tokyo-metropolitan-gov/covid19/blob/master/FORKED_SITES.md
