### ISSUE TITLE
都内表記を県内へ変更

### ISSUE THREAD

**Issue by sandats** [codeforkagoshima/covid19#107]
## 改善詳細 / Details of Improvement
- 検査実施数の表示が「都内」となってしまっている。

## スクリーンショット / Screenshot
![スクリーンショット 2020-04-08 18 16 48](https://user-images.githubusercontent.com/26110942/78767163-31d85200-79c5-11ea-90e1-f21d74d20576.png)

## 期待する見せ方・挙動 / Expected behavior
- 「県内」に変更すると良いと思いました。

**Comment by hinapa** [comment]
わ、ホントですね
