### ISSUE TITLE
GMOペパボ株式会社による提供である旨の文言を追加する

### ISSUE THREAD

**Issue by kentaro** [codeforkagoshima/covid19#13]
## 改善詳細 / Details of Improvement

- サーバーおよびドメインの提供会社である[GMOペパボ株式会社](https://pepabo.com/)のクレジットを追加する

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/3458/76705385-13af6700-6723-11ea-8e42-adbf00f01aa2.png)
![image](https://user-images.githubusercontent.com/3458/76705390-1b6f0b80-6723-11ea-9cc3-14438f61724d.png)

## 議論するべきポイント / Points to Discuss

- 関係者による合意が必要だろうと思われます。

**Comment by kurotaky** [comment]
@hinapa cc/ @codeforkagoshima/developers 
Facebookグループの `COVID-19対策サイト＠鹿児島県版つくる` 内でみなさんに共有しました 👍

**Comment by kentaro** [comment]
こちらでご案内いただきました！
https://www.facebook.com/groups/614866925912447/permalink/616074685791671/
