### ISSUE TITLE
Google AnalyticsのID差し替え or 撤去

### ISSUE THREAD

**Issue by kurehajime** [codeforkagoshima/covid19#15]
## 改善詳細 / Details of Improvement
- Google AnalyticsのIDが東京都のままなので、これは差し替え or 撤去した方が良いかと思います。

## 該当箇所

[鹿児島版](https://github.com/codeforkagoshima/covid19/blob/bb30d3cedf12d5a3416d5177e23ea24bdc6ae921/nuxt.config.ts#L201)も[東京版](https://github.com/tokyo-metropolitan-gov/covid19/blob/08a81ec05e8d333729f9fa8f4e1c9543a84c5d35/nuxt.config.ts#L157)もいずれも

```
  googleAnalytics: {
    id: 'UA-159417676-1'
  },
```
となっています。

## 期待する見せ方・挙動 / Expected behavior
- 鹿児島版を所轄する管理者のGoogle AnalyticsのIDに差し替える
- または暫定措置としてGoogle Analyticsの撤去

## 動作環境・ブラウザ / Environment
- macOS  10.15.3（19D76）
- Chrome 80.0.3987.132

**Comment by kurotaky** [comment]
@kurehajime 
ありがとうございます。一旦撤去で良いと思いました 👍

**Comment by akht** [comment]
[ここ](https://hackmd.io/@homata/ryHz3P4BI#%E3%82%BD%E3%83%BC%E3%82%B9%E7%B7%A8)にも記載がありますね〜。

>または暫定措置としてGoogle Analyticsの撤去

@kurehajime 私もこちらがいいと思いました:+1:

**Comment by kurehajime** [comment]
↑
撤去版のPull Request作ってみました。
