### ISSUE TITLE
フロー図の扱い

### ISSUE THREAD

**Issue by kurehajime** [codeforkagoshima/covid19#21]
## 改善詳細 / Details of Improvement

下記リンクでもご相談したのですが、フロー図が東京都のままになっています。
間違った案内してしまうのは危険なので修正したいのですが、
東京都と鹿児島県では体制が異なる可能性もあり、電話番号を置き換えるだけの修正では不十分の可能性があります。
なので、一旦撤去するのはどうでしょうか？

https://www.facebook.com/groups/614866925912447/permalink/616723865726753/

## 期待する見せ方・挙動 / Expected behavior
- フロー図の一時撤去。
- または鹿児島県の体制を反映したバージョンに修正。

**Comment by kurotaky** [comment]
一旦撤去で良いと思いました 👍
