### ISSUE TITLE
GoogleAnalyticsへの対応

### ISSUE THREAD

**Issue by hinapa** [codeforkagoshima/covid19#46]
## 改善詳細 / Details of Improvement
- サイトの閲覧状況を把握したい

**Comment by kurehajime** [comment]
もともと東京版にはあったのを削除した経緯があるので、IDさえとれれば技術的にはすぐできます。

https://github.com/codeforkagoshima/covid19/issues/15

**Comment by hinapa** [comment]
ID用意しました
UA-161769692-1

**Comment by kurehajime** [comment]
ありがとうございます！
