### ISSUE TITLE
SP版でヘッダーのタイトルテキストの表示が窮屈になっている(画像参照)

### ISSUE THREAD

**Issue by qst-exe** [codeforkagoshima/covid19#61]
## 改善詳細 / Details of Improvement
- ヘッダー幅まで「鹿児島県新型コロナウイルスまとめサイト」が表示してから改行されてほしい

## スクリーンショット / Screenshot
![Screenshot_20200325-232727_Firefox](https://user-images.githubusercontent.com/7909367/77547421-845b3e00-6ef0-11ea-921b-54ea61067e4d.jpg)

## 動作環境・ブラウザ / Environment
- Android
- Chrome / Firefox

**Comment by hinapa** [comment]
そこめちゃ気になってましたw

**Comment by qst-exe** [comment]
見つけた流れで修正します！
