### ISSUE TITLE
web検索からの閲覧を増やしたい

### ISSUE THREAD

**Issue by hinapa** [codeforkagoshima/covid19#94]
## 改善詳細 / Details of Improvement
-検索しても出てこないのをなんとかしたい（SEO対策？）

**Comment by yukitaka13-1110** [comment]
SEOは大丈夫そうですね
ドメイン依存なところとインデックスまで時間がかかるところですかね🤔？
<img width="1677" alt="スクリーンショット 2020-04-14 12 35 02" src="https://user-images.githubusercontent.com/22259776/79183441-709a5c00-7e4c-11ea-9903-a95258560d8a.png">

**Comment by hinapa** [comment]
おー！ありがとう御座います！
なるほど、しばらく待ってるとボチボチ上がってくる感じなんですねー。
というか、こういうツールがあるんですね！ふむふむ
