### ISSUE TITLE
リモートで飲みたい

### ISSUE THREAD

**Issue by hinapa** [codeforkagoshima/covid19#96]
## 改善詳細 / Details of Improvement
せっかくの機会なので、どっかのタイミングにリモートで飲みたい

**Comment by MakotoSako** [comment]
ZOOM飲み会、してみたいですね。

**Comment by kurotaky** [comment]
いいですね 👍

**Comment by hinapa** [comment]
開催できたけどペパボさんメンバーいなかったので、また今度やりましょ〜
